import pygame
from time import  sleep
pygame.init()
window = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
pygame.mixer.init()
pygame.mixer.music.load('horror-sound.wav')
pygame.mixer.music.play()
sleep(8)
pygame.mixer.music.load('scary-2.wav')
pygame.mixer.music.play()
sleep(0.9)
image = pygame.image.load('ghost.jpg')
window.blit(image, (0, 0))
pygame.display.update()
sleep(3)
